namespace ScreenCaptureNativeComponent
{
	interface IScreenCaptureService
	{
		Windows.Foundation.IAsyncAction StartCaptureAsync();
		void StopCapture();
		void VerifyDuration();
		Windows.Foundation.IAsyncAction SetupMediaComposition();
		Windows.Foundation.IAsyncAction RenderCompositionToFile(Windows.Storage.StorageFile file, Windows.UI.Xaml.Controls.ProgressBar progressBar);
		Windows.Foundation.IAsyncAction WaitForImageRenderring();
	};
    
    runtimeclass ScreenCaptureService: [default] IScreenCaptureService
    {
		ScreenCaptureService();
	}
}
