namespace ScreenCaptureComponent
{
    [default_interface]
    runtimeclass CaptureHelper
    {
		CaptureHelper();
		void StartCaptureInternal(Windows.Foundation.TimeSpan span,Windows.Media.Editing.MediaComposition mediaComps,Windows.Graphics.Capture.GraphicsCaptureItem item);
		void Stop();
    }
}
